version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: